2024-04-08 10:50:33,304 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.16.3.169:45013'
2024-04-08 10:50:33,927 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-worker-space/worker-en5yh6yu', purging
2024-04-08 10:50:35,035 - distributed.worker - INFO -       Start worker at:   tcp://172.16.3.169:36941
2024-04-08 10:50:35,035 - distributed.worker - INFO -          Listening to:   tcp://172.16.3.169:36941
2024-04-08 10:50:35,035 - distributed.worker - INFO -           Worker name:             SLURMCluster-4
2024-04-08 10:50:35,035 - distributed.worker - INFO -          dashboard at:         172.16.3.169:41740
2024-04-08 10:50:35,035 - distributed.worker - INFO - Waiting to connect to:    tcp://172.16.3.97:42899
2024-04-08 10:50:35,035 - distributed.worker - INFO - -------------------------------------------------
2024-04-08 10:50:35,035 - distributed.worker - INFO -               Threads:                         36
2024-04-08 10:50:35,035 - distributed.worker - INFO -                Memory:                 139.70 GiB
2024-04-08 10:50:35,035 - distributed.worker - INFO -       Local Directory: /tmp/dask-worker-space/worker-uwati_89
2024-04-08 10:50:35,035 - distributed.worker - INFO - -------------------------------------------------
2024-04-08 10:50:35,043 - distributed.worker - INFO -         Registered to:    tcp://172.16.3.97:42899
2024-04-08 10:50:35,043 - distributed.worker - INFO - -------------------------------------------------
2024-04-08 10:50:35,044 - distributed.core - INFO - Starting established connection to tcp://172.16.3.97:42899
/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in divide
  return func(*(_execute_task(a, cache) for a in args))
/vortexfs1/home/anthony.meza/mambaforge/envs/atm_rivers/lib/python3.10/site-packages/dask/core.py:119: RuntimeWarning: invalid value encountered in divide
  return func(*(_execute_task(a, cache) for a in args))
slurmstepd: error: *** JOB 388435 ON pn119 CANCELLED AT 2024-04-08T12:50:50 DUE TO TIME LIMIT ***
